name: CI pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest autopep8
          npm install eslint@8.10.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8 and fix issues with autopep8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --ignore=E501 --statistics
          autopep8 --in-place --recursive .

      - name: Run ESLint with fix option
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx
          --format stylish
          --fix
        continue-on-error: true

      - name: Test with pytest
        run: |
          pytest
